### ISSUE TITLE
Download file pattern

### ISSUE THREAD

**Issue by s1lverkin** [chibicitiberiu/ytsm#23]
Is there any way to add another file patterns other than described in settings? I would like to have reverse playlist index, because IMO it's not good to have newest videos to have first numbers (e.g. S01E001) it should be reversed.

**Comment by chibicitiberiu** [comment]
Hmm, that complicates things a bit.

I only noticed this right now... the Uploads playlist is actually reversed, so the newest videos are added to the top of the playlist.

Right now, no, there's no way to do that. But we should handle this case.

**Comment by Nixon506E** [comment]
I am also thinking having the option to have a different download pattern per subscription if one shouldnt follow the default.

**Comment by chibicitiberiu** [comment]
The playlist order issue should be solved. Channels are now handled differently than normal playlists.

Note that existing subscriptions won't be fixed, the fix only works for new subscriptions (the index is fixed when new videos are added).
