### ISSUE TITLE
Please make it fully self hosted

### ISSUE THREAD

**Issue by gerroon** [chibicitiberiu/ytsm#31]
Hi

It looks like this app is loading some external scripts from cloudflare and bootstrap, as of now I personally  would not call it a self hosted solution. Please make the scripts to be loaded locally. If there is a way to make them offline please provide the steps in the documentation

thanks

**Comment by J-tt** [comment]
We'll definitely look at implementing this, for now look at Disconnect (a browser extension) which caches CDN scripts.

**Comment by chibicitiberiu** [comment]
Using CDN can make loading the pages faster, as the browser may have already cached these script/CSS files. We could add a global settings `ALLOW_CDN=True/False`.

**Comment by rytilahti** [comment]
I think this is also related: the import does not function properly if decentraleyes is in use (it will produce a warning, even when the entries are imported properly).

**Comment by chibicitiberiu** [comment]
Should be fixed now.
