### ISSUE TITLE
Question: Docker Volume Mapping

### ISSUE THREAD

**Issue by dannyhanes** [chibicitiberiu/ytsm#38]
I know next to nothing about docker, but I have managed to get the webapp up and working. My question is this. I have a volume mapped on my ubuntu server where docker is running at `/media/youtube` and I just cant figure out what line to change in the `docker-compose.yml` to make sure that all subscriptions use `/media/youtube` as the root path for downloads. 

Thanks!

**Comment by chibicitiberiu** [comment]
Currently, if you open the dockerfile, you will see there are 2 volumes.
One of them is the config folder, the other is the data directory. Right
now, files are downloaded to data/videos.

I am considering adding a separate volume for the downloads, but for now
this is how it works.

It is possible to change it by modifying the dockerfile yourself (add a new
volume for downloads, map it in the compose or whatever your setup is, and
then modify config/config.ini to use that folder).

**Comment by bsquidwrd** [comment]
@dannyhanes You're looking for this line: https://github.com/chibicitiberiu/ytsm/blob/0becefbacf0995a16e215f6eaac132439a1af68d/docker-compose.yml#L22
