### ISSUE TITLE
which config?

### ISSUE THREAD

**Issue by gerroon** [chibicitiberiu/ytsm#53]
Hi

Can you please tell me which config does Ytsm uses? I am abit confused since there arew multiple config and default files around default.

thanks

**Comment by chibicitiberiu** [comment]
To put it simply:
* `default.ini` - these are the defaults, if nothing is set for that option in `config.ini`. It doesn't need to be modified.
* `config.ini` - this is the right config file
* environment variables - they override `config.ini`, mostly useful in docker

In PR #52 I completely removed `default.ini`, and moved a lot of options from the config file to the application itself. Only a few options that cannot be modified at runtime are set from `config.ini`, such as the database.

**Comment by gerroon** [comment]
Thanks, do I need to updte the db when I make changes to the config ini file?

**Comment by chibicitiberiu** [comment]
There are 2 cases where you need to re-run migrations
* when you update the application.
* if you modify the database settings (for example, using a different database system, or modifying the database filename) in config.ini

**Comment by gerroon** [comment]
ok thanks
