### ISSUE TITLE
Better file naming

### ISSUE THREAD

**Issue by gerroon** [chibicitiberiu/ytsm#57]
Hi

The downloaded videos have all this mambo jambo in their files names like " [lLAWq45bvIU]" It would be nice if there is  a way to get rid of them.

I know that is a youtube-dl thing, so why not give the user an option to override the default naming pattern?

**Comment by Ruthalas** [comment]
I assume the "mambo-jambo" is the unique video ID.
If you do decide to make a change regarding the inclusion of that data, please make it possible to have the video ID if the user _does_ want it.
It's pretty vital if you ever want to work with the files later.

(I'm all for having a toggle, or user-configurable naming patterns!)

**Comment by chibicitiberiu** [comment]
Look again in the settings. There is a file pattern field.

**Comment by gerroon** [comment]
ashamed :( 

Will changing the file pattern make Ytsm to loose track of past files?

**Comment by chibicitiberiu** [comment]
No, they are stored in the db.

**Comment by gerroon** [comment]
ok thanks
