### ISSUE TITLE
NON ISSUE: So Fancy :)

### ISSUE THREAD

**Issue by gerroon** [chibicitiberiu/ytsm#59]
The new video info page feels so fancy, cool job!

It would be nice if the playing opens a new tab. 

The next step should be playing in the thumbnails (via some play play)  :) That would be even fancier

**Comment by chibicitiberiu** [comment]
> It would be nice if the playing opens a new tab.
That is a good idea, pretty simple to fix.

> The next step should be playing in the thumbnails (via some play play) :) That would be even fancier
This is pretty difficult to do. I think FFMPEG might be able to generate thumbnails of downloaded videos, but it might take a significant amount of time to implement it, it won't work on videos that are not downloaded (they might have to be downloaded first). I'm not going to do this, but if anyone is willing to make a PR, I would gladly accept it.

**Comment by chibicitiberiu** [comment]
Fixed in commit https://github.com/chibicitiberiu/ytsm/commit/18f2557cb9d21ec7da673566c2aaabb8b85d4c5d.
