### ISSUE TITLE
Improve docker support

### ISSUE THREAD

**Issue by chibicitiberiu** [chibicitiberiu/ytsm#6]
* I think it would be better to only copy in the app and not the config
* I think the docker image itself should be responsible for running the init.sh and not the docker compose file
* I think the docker image should be published to docker hub from this repo (Only @chibicitiberiu can set this up, I setup a fork to build but only he or someone with repo access can do that so that it's up to date)
* Config/data should be VOLUME'd and port should be EXPOSED'd

All of this would allow for someone to do the following:

```
$ docker pull chibicitiberiu/ytsm
$ docker run chibicitiberiu/ytsm -v /path/to/my/config:/config -v /path/to/my/media:/media
```

The docker compose file is a nice touch but I think it currently has too much "Responsibility" as in the docker image should stand on it's own and the docker compose file should make use of that image and setup other things (nginx/db) so that people can use their own reverse proxy/db but the compose file is an example of how to get things up and running quick (to that end I think the default should be sqlite with an option to use another DB). 

I'm not sure if this is the best place to discuss this and I'm happy to move the discussion to an issue or elsewhere.

Edit: Also I think we need a way to move the DB config out of settings.py so that it can be set via the INI config file

_Originally posted by @joshstrange in https://github.com/chibicitiberiu/ytsm/pull/1#issuecomment-434385465_

**Comment by PBXg33k** [comment]
While the config can already be volume'd, wouldn't it be more convenient to set the defaults in the config file as environment variables so this could be passed to the container?

**Comment by chibicitiberiu** [comment]
Paging @J-tt and @joshstrange who are more familiar with Docker.

**Comment by joshstrange** [comment]
@PBXg33k Yeah, I would use ENV's with the current defaults as fallbacks. Most libraries/lang have some method of `getEnvVariableOrFallbackTo("MY_ENV_VAR", "fallbackValue");` to make this easy. 

Maybe even: ENV > Config File > Defaults 

( ">" = greater than, not arrows)

That way people can continue to use the config file.

I've taken a look at the code (I've only ever used python as bash++, it's not one of my primary languages) and it shouldn't be terribly hard. I will admit I was a little confused as I think @J-tt's merge may have left in values/variable that are no longer used (settings.py vs the config.ini, there are overlaps). So I'd have to track that down first but after all the settings are in 1 place making it respect ENV's should be really easy.

So I'm thinking the next few steps (which I don't know when I'll have time to work on) are:

1. Get all settings defined in 1 place (Including DB settings, API keys, directories, limits/etc)

2. Make sure settings exist outside of main app folder 

3. Write or use existing function to handle getting config from environment variables, then config file, then fallback to defaults.

4. Modify Dockerfile to expose it's port, offer downloads/config as volumes to mount, run the init script itself


In my experience the best docker containers can run standalone with no arguments/mounts (obviously not persisting to anything but the container in that scenario). It lets people get started in seconds and then after they play around in the app and decide it's for them they can start over mounting to the host.

**Comment by J-tt** [comment]
Yeah, this initial PR was to provide a more stable and easier option for people to get the project up and running on their local machines.

I was having some issues running init.sh in the Dockerfile, so I moved it to docker-compose with the TTY flag (I'll see if I can find the StackOverflow thread for that).

I agree, using environmental variables would significantly improve the script, especially in regards to the api key.

I'll work on getting a stand alone Dockerfile with sqlite running, it just worked better with the current codebase to have a docker-compose file, as it'll require a decent amount of modifications to settings.py to get it to consume environmental variables (although I don't have a huge amount of experience with that.

**Comment by PBXg33k** [comment]
I've written an init script for one of my projects which bootstraps the docker container using shell scripts. Maybe we can use that as a starting point if that's relevant?

I use this approach for backward compatibility, ie: setting config.ini/json file based on evironment values using jq and such

https://github.com/PBXg33k/ExHentai-Archive/blob/dev/init.d.sh
kicks off all shell scripts in the following dir.
https://github.com/PBXg33k/ExHentai-Archive/tree/dev/docker-entrypoint-init.d

**Comment by PBXg33k** [comment]
@joshstrange Sorry to address you separately. Saw your comment after i posted previous message.

I agree with you on the points, i would fork and patch on my end if i had the time to work on it, but that would be a hack/workaround with minimal changes to the python code because my lack of experience with it.

**Comment by chibicitiberiu** [comment]
I forgot to remove some options from `settings.py` (such as YT API key, and a few others) that I used in early development, I can clean that up.

The `config.ini` parser supports using environment variables using the syntax ${env:SOMETHING}, perhaps we could provide a `config.docker.ini` which takes configuration from environment variables.

I agree that database should also be included in `config.ini`. I think it is possible to build the `settings.py` file dynamically at runtime, I've seen examples where they checked an environment variable for selecting between development and production. There's also #7 which involves cleaning up `settings.py`.

I have a busy week, not sure if I can get anything done until Saturday, if someone wants to take that until then, let me know.

**Comment by PBXg33k** [comment]
Regarding database, does Django support (full) database DSN? That would enable users to pass one variable containing all info to the container.

**Comment by chibicitiberiu** [comment]
According to [Django's documentation](https://docs.djangoproject.com/en/2.1/ref/databases/#full-dsn-and-easy-connect), yes.

**Comment by PBXg33k** [comment]
I'll try and work on adjusting the Dockerfiles in such a manner that it should be easy to setup with docker-compose and stack using environment variables and volumes.

Want to deploy this on my own swarm so have personal benefit aswel

**Comment by bsquidwrd** [comment]
I just made a PR #21 
Please take a look and let me know if that would solve this or if I'm at least on the right track

**Comment by bsquidwrd** [comment]
@J-tt Would you mind explaining the `tty` option in the docker-compose file? I'm not too familiar with it.

I also noticed in testing that migrate fails if the database starts a second or two later than web. Any thoughts on how to fix this?

**Comment by chibicitiberiu** [comment]
@bsquidwrd [Here's](https://docs.docker.com/compose/startup-order/) what docker documentation says.
Apparently, they use a 'wait-for-it' script which waits until the database starts listening on TCP.

**Comment by bsquidwrd** [comment]
@chibicitiberiu Due to our conversation in #21 and having SQLite as the default, I'm not going to worry too much about migrations failing and will just add a note in my docker readme as part of the PR

**Comment by chibicitiberiu** [comment]
Yeah, those should be fine, although if anyone started using the app, he might see the data disappear when moving to SQLite.

**Comment by bsquidwrd** [comment]
When swapping version/database hosts etc it's on the person running it. With this, it will allow them to set the environment variables to point to the old database before running but is on them to do that :/

**Comment by chibicitiberiu** [comment]
I made some progress, all the relevant settings from `settings.py` can now be modified through the config.ini file. I have a few things left to do, so I'll push the commits after that.

**Comment by bsquidwrd** [comment]
@chibicitiberiu If I may make a suggestion.

Either make a dev branch and do your in-progress code there then submit a PR to your master branch when it's tested and ready or utilize tags and have versions of the project. That way when people pull the Docker image, there won't be a mix of versions available.

I personally recommend using tags, that way the Docker images get tagged with a version as well if you setup your Build Settings like so, instead of building on the master branch [https://i.imgur.com/UVvaoer.png](https://i.imgur.com/UVvaoer.png)

**Comment by chibicitiberiu** [comment]
Docker hub should [also be up and running](https://hub.docker.com/r/chibicitiberiu/ytsm/), and I think I got it set up correctly.

**Comment by J-tt** [comment]
@bsquidwrd I was having issues getting console output without the tty option, I'm not sure if that's still the case, as I was playing around with several options when building it.

Sorry for my radio silence by the way, I'm currently in the middle of exams in Australia, so I haven't been able to put aside much time.

Looks like you guys have got this setup pretty well!

**Comment by bsquidwrd** [comment]
@J-tt No worries. TTY can stay for now as a compose option then.

Good luck on exams!

**Comment by J-tt** [comment]
@bsquidwrd Thanks!

I'm gonna look at squashing some other issues in the repo, I think the docker container is in a solid enough state now 👍

**Comment by chibicitiberiu** [comment]
I finished the merge, so looks like this is done.
