### ISSUE TITLE
Feature Request: Automatically move to the next available video after watching.

### ISSUE THREAD

**Issue by cyberjacob** [chibicitiberiu/ytsm#74]
Looking to recreate the functionality from the (now broken) Video Deck for YouTube.

The feature in particular I'm looking for it to automatically move to the next available video when the current one has been watched. Off the top of my head, this could be done through javascript on the ytsm page or a temporary playlist in YouTube. I'm not sure which one Video Deck used.

Obviously this would need to be optional. As a suggestion there could be a dedicated button at the top of the video list page to handle this?

**Comment by girlpunk** [comment]
Implemented by #87
